# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='handdryers',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='handicapstalls',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='papertowels',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='sinks',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='stalls',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='windows',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
