# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0002_auto_20170401_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bathroom',
            old_name='handdryers',
            new_name='hand_dryers',
        ),
        migrations.RenameField(
            model_name='bathroom',
            old_name='handicapstalls',
            new_name='handicap_stalls',
        ),
        migrations.RenameField(
            model_name='bathroom',
            old_name='papertowels',
            new_name='paper_towels',
        ),
    ]
