# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0003_auto_20170401_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bathrooms.Bathroom')),
            ],
        ),
    ]
