# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='cleanliness_rating',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
