# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0005_rating_cleanliness_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='bathroom_id',
            new_name='bathroom',
        ),
    ]
