# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0007_auto_20170401_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='smell_rating',
            new_name='design_rating',
        ),
    ]
