# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0008_auto_20170401_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='size_rating',
        ),
    ]
