# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0010_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
