# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0011_remove_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='design_rating',
            new_name='amenities_rating',
        ),
    ]
