# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='gender',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
