# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0014_auto_20170401_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='google_maps_link',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='human_readable_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
