# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0015_auto_20170401_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='google_maps_link',
            field=models.CharField(max_length=500),
        ),
    ]
