# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0016_auto_20170401_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='google_maps_embed',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='google_maps_link',
            field=models.CharField(max_length=50),
        ),
    ]
