# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0018_auto_20170401_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bathrooms.Location'),
            preserve_default=False,
        ),
    ]
