# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathrooms', '0019_bathroom_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='location_desc',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
